import type { Property } from '../types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop_1',
    address: {
      street: '47 Oak Ridge Drive',
      city: 'Freehold',
      state: 'NJ',
      zip: '07728',
      lat: 40.2615,
      lng: -74.2773,
      formattedAddress: '47 Oak Ridge Drive, Freehold, NJ 07728',
    },
    price: 549000,
    beds: 4,
    baths: 2.5,
    sqft: 2400,
    lotSqft: 9500,
    yearBuilt: 1998,
    propertyType: 'single-family',
    status: 'active',
    daysOnMarket: 8,
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    ],
    description: 'Beautiful colonial on a quiet cul-de-sac. Updated kitchen with granite counters, hardwood floors throughout, large master suite with walk-in closet. Fenced backyard, attached 2-car garage. Close to Route 9 and NJ Transit.',
    features: ['Updated Kitchen', 'Hardwood Floors', 'Fenced Yard', '2-Car Garage', 'Master Bath'],
    neighborhood: {
      walkScore: 42,
      transitScore: 35,
      schoolRating: 8,
      crimeIndex: 28,
      medianHomePrice: 520000,
      priceChangePct12m: 4.2,
    },
    aiInsights: {
      matchScore: 94,
      pros: ['Within budget', 'Matches bed/bath needs', 'Good school rating (8/10)', 'Short commute to Route 9'],
      cons: ['No virtual tour available', 'HOA fees unknown', 'Slightly older mechanicals'],
      summary: 'Strong match for your profile. This property ticks most of your boxes — 4 bedrooms, great schools, and room to grow. The updated kitchen and yard align well with your must-haves.',
      commuteMinutes: 28,
      estimatedMonthlyCost: 3200,
    },
    listedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_2',
    address: {
      street: '112 Maple Court',
      city: 'Marlboro',
      state: 'NJ',
      zip: '07746',
      lat: 40.3148,
      lng: -74.2595,
      formattedAddress: '112 Maple Court, Marlboro, NJ 07746',
    },
    price: 489000,
    beds: 3,
    baths: 2,
    sqft: 1950,
    lotSqft: 8000,
    yearBuilt: 2004,
    propertyType: 'single-family',
    status: 'active',
    daysOnMarket: 3,
    photos: [
      'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800&q=80',
      'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&q=80',
    ],
    description: 'Move-in ready ranch-style home in desirable Marlboro. Open floor plan, renovated baths, newer roof (2021). Fantastic Marlboro school district. Minutes to NJ Transit train station.',
    features: ['Open Floor Plan', 'New Roof', 'Renovated Baths', 'Near Train Station'],
    neighborhood: {
      walkScore: 38,
      transitScore: 55,
      schoolRating: 9,
      crimeIndex: 19,
      medianHomePrice: 490000,
      priceChangePct12m: 6.1,
    },
    aiInsights: {
      matchScore: 88,
      pros: ['Top-rated schools (9/10)', 'Close to NJ Transit', 'Under budget', 'Newer construction'],
      cons: ['One fewer bedroom than preferred', 'Smaller lot', 'Rising quickly — may get offers fast'],
      summary: 'Excellent value with top schools and train access. At 3 beds it\'s one short of your target, but the school rating and commute convenience are exceptional.',
      commuteMinutes: 19,
      estimatedMonthlyCost: 2900,
    },
    listedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_3',
    address: {
      street: '8 Willow Glen Road',
      city: 'Howell',
      state: 'NJ',
      zip: '07731',
      lat: 40.1837,
      lng: -74.1946,
      formattedAddress: '8 Willow Glen Road, Howell, NJ 07731',
    },
    price: 599000,
    beds: 5,
    baths: 3,
    sqft: 3100,
    lotSqft: 15000,
    yearBuilt: 2012,
    propertyType: 'single-family',
    status: 'active',
    daysOnMarket: 14,
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    ],
    description: 'Spacious 5-bedroom colonial on a large lot. Gourmet kitchen, finished basement, in-ground pool. Master suite with spa bath. 3-car garage. Perfect for large families or multi-generational living.',
    features: ['Pool', 'Finished Basement', 'Gourmet Kitchen', '3-Car Garage', 'Large Lot'],
    neighborhood: {
      walkScore: 28,
      transitScore: 22,
      schoolRating: 7,
      crimeIndex: 24,
      medianHomePrice: 565000,
      priceChangePct12m: 3.8,
    },
    aiInsights: {
      matchScore: 79,
      pros: ['Most space on your list', 'Pool and large yard', 'Finished basement adds flex space', 'Priced well per sq ft'],
      cons: ['Above max budget', 'Longer commute (38 min)', 'Higher maintenance costs expected'],
      summary: 'The most spacious option and the only one with a pool and finished basement, but it stretches your budget. Worth a look if space is the priority.',
      commuteMinutes: 38,
      estimatedMonthlyCost: 3750,
    },
    listedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_4',
    address: {
      street: '223 Princeton Boulevard',
      city: 'Freehold',
      state: 'NJ',
      zip: '07728',
      lat: 40.2559,
      lng: -74.2741,
      formattedAddress: '223 Princeton Boulevard, Freehold, NJ 07728',
    },
    price: 425000,
    beds: 3,
    baths: 2,
    sqft: 1750,
    lotSqft: 6500,
    yearBuilt: 1988,
    propertyType: 'single-family',
    status: 'pending',
    daysOnMarket: 5,
    photos: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    ],
    description: 'Updated bi-level in Freehold Borough. New HVAC 2023, updated kitchen and master bath. Walking distance to downtown Freehold, restaurants, and shops.',
    features: ['New HVAC', 'Updated Kitchen', 'Master Bath', 'Walk to Downtown'],
    neighborhood: {
      walkScore: 72,
      transitScore: 45,
      schoolRating: 7,
      crimeIndex: 35,
      medianHomePrice: 420000,
      priceChangePct12m: 5.5,
    },
    aiInsights: {
      matchScore: 82,
      pros: ['Most walkable option', 'Well under budget', 'New systems (lower maintenance risk)', 'Downtown convenience'],
      cons: ['Currently pending', 'Older home style', 'Smaller lot'],
      summary: 'Best walkability score on your list and well under budget. Currently pending but worth watching — deals fall through. New HVAC is a significant plus.',
      commuteMinutes: 25,
      estimatedMonthlyCost: 2600,
    },
    listedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
